exclude: ".*\\.csv"
repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v2.4.0
    hooks:
      - id: flake8
        # line too long and line before binary operator (black is ok with these)
        types:
          - python
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        args: ["--unsafe"]
      - id: check-added-large-files
  - repo: https://github.com/psf/black
    rev: 19.10b0
    hooks:
      - id: black
