name: CI

on:
  workflow_dispatch:
  push:
  pull_request:
  release:
    types: [published]

jobs:
  run-if:
    name: "Run If"
    runs-on: ubuntu-latest
    if: github.event_name != 'pull_request' || github.event.pull_request.head.repo.fork == false
    steps:
      - run: |
          echo "Running CI"
  test-python:
    name: "Test Python Version"
    needs: ["run-if"]
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        # Checks based on python versions ---
        python-version: ['3.8', '3.9', '3.10']
        requirements: [""]

    steps:
      - uses: actions/checkout@v2

      # setup docker and gcp authentication ----
      #
      - name: Run docker-compose
        run: |
          docker-compose up --build -d

      - name: Set up Cloud SDK
        uses: google-github-actions/setup-gcloud@master
        with:
          project_id: siuba-tests
          service_account_key: ${{ secrets.GCP_SA_KEY }}
          export_default_credentials: true

      # install python w/ dependencies, and run tests ----
      #
      - uses: actions/setup-python@v2
        with:
          python-version: "${{ matrix.python-version }}"
      - name: Install dependencies from requirements file
        run: |
          python -m pip install --upgrade pip

          # optionally install a requirements file
          if [[ ! -z "${REQUIREMENTS}" ]]; then
            python -m pip install -r "${REQUIREMENTS}"
          fi

          # install package with dev dependencies
          python -m pip install .[dev]

        env:
          REQUIREMENTS: ${{ matrix.requirements }}

      - name: Run tests
        run: |
          pytest
        env:
          SB_TEST_MYSQLPORT: 3307
          SB_TEST_PGPORT: 5433

          SB_TEST_BQDATABASE: ""
          SB_TEST_BQPROJECT: dbcooper-tests

          SB_TEST_SNOWFLAKEDATABASE: "DBCOOPER_DB1"
          SB_TEST_SNOWFLAKEUSER: "DBCOOPER_CI"
          SB_TEST_SNOWFLAKEPASSWORD: ${{ secrets.SB_TEST_SNOWFLAKEPASSWORD }}
          SB_TEST_SNOWFLAKEHOST: "qf04441.us-east-2.aws"
          SB_TEST_SNOWFLAKEOPTIONS: "warehouse=COMPUTE_WH&role=USER_DBCOOPER_CI"


  build-docs:
    name: "Build Docs"
    needs: ["run-if"]
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: "3.10"
      - name: Install dependencies from requirements file
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements/dev.txt
      - name: Build docs
        run: |
          make docs-build
